name: Run Job Matcher Flow

on:
  schedule:
    - cron: '0 */12 * * *'  # Ejecuta cada 12 horas
  workflow_dispatch:        # También permite ejecución manual     # También se puede correr manualmente

jobs:
  run-job-matcher:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export env variables
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> $GITHUB_ENV
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV
          echo "N8N_WEBHOOK_URL=${{ secrets.N8N_WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Run Crawler
        run: python src/main.py

      - name: Run Matcher
        run: python src/batch_matcher.py

      - name: Notify n8n webhook
        run: |
          curl -X POST $N8N_WEBHOOK_URL \
            -H "Content-Type: application/json" \
            -d '{"status":"matcher_complete"}'
